version: "2"
services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    networks:
      - iotnet

  mysql:
    image: mysql:5
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: root
    networks:
      - iotnet
      
  grafana:
    image: grafana/grafana:6.5.0
    ports:
      - "3000:3000"
    networks:
      - iotnet

  telegraf:
    image: telegraf:1.26
    networks:
      - iotnet
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - influxdb
      - mosquitto

  mosquitto:
    image: eclipse-mosquitto:latest
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/conf/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log
    networks:
      - iotnet
  
  coap-server:
    environment:
      INFLUX_HOST: "influxdb"
    container_name: coap-server
    build:
      context: ./coap-server
      dockerfile: Dockerfile
    networks:
      - iotnet
    ports:
      - "5683:5683/udp"
    depends_on:
      - influxdb
    
networks:
  iotnet:
    driver: bridge
